#define BUILD_COMMIT_ID "d9d2e6e"
#define PROJECT_VERSION "2.1.3f-Release"
#define PROJECT_VERSION_BUILD_NO "d9d2e6e"
#define PROJECT_VERSION_LONG PROJECT_VERSION " (" "d9d2e6e" ")"
#define VERSION_MAJOR "2"
#define VERSION_MINOR "1.3f-Release"
#define VERSION_PATCH "d9d2e6e"
